#!/usr/bin/env zsh

# ORDER
SPACESHIP_PROMPT_ORDER=(
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  swift         # Swift section
  xcode         # Xcode section
  docker        # Docker section
  aws           # Amazon Web Services section
  pyenv         # Pyenv section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_PROMPT_DEFAULT_PREFIX='| '

# Char
SPACESHIP_CHAR_SYMBOL='\uf1d1 ➜ '

# DIR
SPACESHIP_DIR_TRUNC_PREFIX=''
SPACESHIP_DIR_TRUNC='0'

# Git
SPACESHIP_GIT_STATUS_COLOR='208'
SPACESHIP_GIT_STATUS_PREFIX=' '
SPACESHIP_GIT_STATUS_SUFFIX=''
SPACESHIP_GIT_STATUS_UNTRACKED='\ufc74 '
SPACESHIP_GIT_STATUS_ADDED='\uf457 '
SPACESHIP_GIT_STATUS_MODIFIED='\uf459 '
SPACESHIP_GIT_STATUS_RENAMED='\uf45a '
SPACESHIP_GIT_STATUS_DELETED='\uf458 '
SPACESHIP_GIT_STATUS_STASHED='\uf692 '
SPACESHIP_GIT_STATUS_UNMERGED='\uf407 '
SPACESHIP_GIT_STATUS_AHEAD='\uf403 '
SPACESHIP_GIT_STATUS_BEHIND='\uf404 '

# Swift
SPACESHIP_SWIFT_SYMBOL='\ufbe3 '

# Xcode
SPACESHIP_XCODE_PREFIX='using '
SPACESHIP_XCODE_SHOW_GLOBAL=false
SPACESHIP_XCODE_SHOW_LOCAL=true
SPACESHIP_XCODE_SYMBOL='🛠  '

# Time
SPACESHIP_EXEC_TIME_COLOR='green'