#!/usr/bin/env bash

# Bootstrap script run by YADM bootstrapper

# TODO: Bootstrap for WSL 2

# Bootstrap with a setup script depending on system
yadm_path="$HOME/.config/yadm"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  $yadm_path/mac/setup
fi

$yadm_path/post_setup

echo "Finished bootstrapping the system! 👍"
