#!/usr/bin/env bash

# Bootstrap setup script depending on system
yadm_path="$HOME/.config/yadm"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  ln -s "$yadm_path/Brewfile" "$HOME/Brewfile"
  brew bundle --file=$HOME/Brewfile
  $yadm_path/mac/setup
  $yadm_path/post_setup
fi

echo "Finished bootstrapping the system! 👍"