#!/usr/bin/env zsh

# Wrapper script to install everything through YADM
# Installs custom binaries onto the system and then bootstraps packages through YADM.
# Created by Lewis Morgan

mac_pre_bootstrap() {
  # Dev tools required for Homebrew
  xcode-select --install

  # Homebrew
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install yadm
  # Setup of packages is done during bootstrap
}

mac_pre_bootstrap

# Clone the dotfiles repository to setup everything else
yadm clone https://github.com/lewismorgan/dotfiles.git --no-bootstrap
brew bundle --file=~/.config/yadm/Brewfile
yadm bootstrap
