#!/usr/bin/env bash

# Wrapper script to install everything through YADM
# Installs custom binaries onto the system and then bootstraps packages through YADM.
# Created by Lewis Morgan

DOTFILES_REPO=https://github.com/lewismorgan/dotfiles.git

mac_install() {
  # Dev tools required for Homebrew
  sudo xcode-select --install
  sudo xcodebuild -license accept

  # Homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install yadm

  # Clone the dotfiles but don't bootstrap it until Homebrew bundle is installed
  yadm clone $DOTFILES_REPO --no-bootstrap
  brew bundle --file=~/.config/yadm/Brewfile
  yadm bootstrap
}

if [ "$system_type" = "Darwin" ]; then
  mac_install
fi
