#!/usr/bin/env bash

# Wrapper script to install everything through YADM
# Installs custom binaries onto the system and then bootstraps packages through YADM.
# Created by Lewis Morgan

system_type=$(uname -s)

mac_pre_bootstrap() {
  # Dev tools required for Homebrew
  xcode-select --install
  
  # Homebrew
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install yadm
  # Setup of packages is done during bootstrap
}

mac_pre_bootstrap

# Clone the dotfiles repository to setup everything else
yadm clone https://github.com/lewismorgan/dotfiles.git --no-bootstrap
brew bundle --file=$HOME/Brewfile
yadm bootstrap

# Change the shell to ZSH --- Keep this as the last line otherwise nothing will run after.
chsh -s $(grep /zsh$ /etc/shells | tail -1)
