#!/usr/bin/env zsh

# Stuff thats not system dependent, used after system setup

#VERSION_NODE=13.6.0
VERSION_RUBY=2.7.1

setup_node() {
  nodenv install $VERSION_NODE

  # Link to Homebrew version
  ln -s /usr/local/opt/node ~/.nodenv/versions/brew

  # Use the homebrew version
  nodenv global brew
}

setup_ruby() {
  # Install plugins
  git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
  git clone https://github.com/rbenv/rbenv-vars.git $(rbenv root)/plugins/rbenv-vars

  rbenv install $VERSION_RUBY

  rbenv global system

  # Install everything from the default-gems file
  cat $(rbenv root)/default-gems | xargs -L 1 gem install -N

  # Turn on rbenv-bundler
  rbenv bundler on
}

# Java Environments to setup
setup_jenv() {
  jenv enable-plugin export
  # Add all java environments using custom jadd script
  #jadd
  # Use system as the global
  jenv global system
}

# ZSH Setup
setup_zsh() {
  mkdir ~/.zinit
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
}

setup_ruby
install_packages
#setup_jenv
setup_zsh
