#!/usr/bin/env bash

# Stuff thats not system dependent, used after system setup

VERSION_NODE=14.12.0
VERSION_RUBY=2.7.1

setup_node() {
  nodenv install $VERSION_NODE

  # Use the homebrew version (system)
  nodenv global system
}

setup_ruby() {
  # Install plugins
  git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
  git clone https://github.com/rbenv/rbenv-vars.git $(rbenv root)/plugins/rbenv-vars

  rbenv install $VERSION_RUBY

  # Use the homebrew version (system)
  rbenv global system

  # Install everything from the default-gems file
  cat $(rbenv root)/default-gems | xargs -L 1 gem install -N

  # Turn on rbenv-bundler
  rbenv bundler on
}

# Java Environments to setup
setup_jenv() {
  jenv enable-plugin export
  # Add all java environments using custom jadd script
  #jadd
  # Use system as the global
  jenv global system
}

setup_apps() {
}

# ZSH Setup
setup_zsh() {
  mkdir ~/.zinit
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
}

setup_ruby
#install_packages
#setup_jenv
setup_apps
# Setting up ZSH is the last step since it will restart the console
setup_zsh
