#!/usr/bin/env zsh

# Stuff thats not system dependent, used after system setup

VERSION_NODE=13.6.0
VERSION_RUBY=2.7.0

install_packages() {
  echo "Installing global yarn packages 🧶"
  cat $HOME/.config/yadm/packages/yarn.txt | xargs -L 1 yarn global add

  echo "Installing vscode packages ⚙️"
  cat $HOME/.config/yadm/packages/vscode.txt | xargs -L 1 code --install-extension
}

setup_node() {
  nodenv install $VERSION_NODE

  # Link to Homebrew version
  ln -s /usr/local/opt/node ~/.nodenv/versions/brew

  # Use the homebrew version
  nodenv global brew
}

setup_ruby() {
  # Install plugins
  git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems

  rbenv install $VERSION_RUBY

  # Link to Homebrew version
  ln -s /usr/local/opt/ruby ~/.rbenv/versions/brew

  # Use the Homebrew version
  rbenv global brew

  # Install everything from the default-gems file
  cat $(rbenv root)/default-gems | xargs -L 1 gem install -N

  # Turn on rbenv-bundler
  rbenv bundler on
}

# Java Environments to setup
setup_jenv() {
  jenv enable-plugin export
  # Add all java environments using custom jadd script
  #jadd
  # Use system as the global
  jenv global system
}

# ZSH Setup
setup_zsh() {
  mkdir ~/.zinit
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
}

setup_ruby
install_packages
setup_jenv
setup_zsh
