#!/usr/bin/env bash

# Initialization script to finish setting up Mac after installing packages

writeDefaults() {
  echo "Writing defaults 🔖"
  # Show hidden files on the system in finder (requires a restart once written. Cmd + Shift + . to display hidden files in open dialogs)
  defaults write com.apple.finder AppleShowAllFiles YES

  # Specify the preferences directory
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.config/iterm2"
  # Use the custom preferences in the directory
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

scheduledTasks() {
  echo "Creating & Hooking launch agents up to launchctl 🚀"

  if [ ! -d "$HOME/Library/LaunchAgents" ]; then
    mkdir $HOME/Library/LaunchAgents
  fi

  ln -s $HOME/.config/.launchd/com.lewisjmorgan.daily.plist $HOME/Library/LaunchAgents
  ln -s $HOME/.config/.launchd/com.lewisjmorgan.weekly.plist $HOME/Library/LaunchAgents

  launchctl load $HOME/Library/LaunchAgents/com.lewisjmorgan.daily.plist
  launchctl load $HOME/Library/LaunchAgents/com.lewisjmorgan.weekly.plist
}

code --install-extension Shan.code-settings-sync

writeDefaults
scheduledTasks

echo "Mac Setup Finished 👨🏼‍💻"
