#!/usr/bin/env bash

# Initialization script to finish setting up Mac after installing packages

writeDefaults() {
  echo "Writing defaults 🔖"
  # Show hidden files on the system in finder (requires a restart once written. Cmd + Shift + . to display hidden files in open dialogs)
  defaults write com.apple.finder AppleShowAllFiles YES

  # iTerm2

  # Specify the preferences directory
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/iterm2"
  # Use the custom preferences in the directory
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

scheduledTasks() {
  echo "Creating & Hooking launch agents up to launchctl 🚀"

  if [ ! -d "$HOME/Library/LaunchAgents" ]; then
    mkdir $HOME/Library/LaunchAgents
  fi

  ln -s $HOME/.launchd/com.lewisjmorgan.daily.plist $HOME/Library/LaunchAgents
  ln -s $HOME/.launchd/com.lewisjmorgan.weekly.plist $HOME/Library/LaunchAgents
  
  launchctl load $HOME/Library/LaunchAgents/com.lewisjmorgan.daily.plist
  launchctl load $HOME/Library/LaunchAgents/com.lewisjmorgan.weekly.plist
}

setup_motd() {
  sudo ln -s $HOME/.yadm/motd /etc/motd
}
# Python3 as default python
ln -s $(brew --prefix)/opt/python/libexec/bin ~/.pyenv/versions/3-brew
# Symlink vscode settings
ln -s "$HOME/.vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"

writeDefaults
scheduledTasks

echo "Mac Setup Finished 👨🏼‍💻"
