#!/usr/bin/env bash

# Bootstrap for 'Yet Another Dotfiles Manager' to setup my environment.
# Created by Lewis Morgan

postinit() {
  setupJenv
  yarnModules
}

# Global npm modules to install
yarnModules() {
  echo "Installing global yarn packages 🧶"
  # Gulp
  yarn global add gulp-cli
  yarn global add create-react-kotlin-app
}

# Java Environments to setup
setupJenv() {
  jenv enable-plugin export
  # Add all java environments using custom jadd script
  ~/.yadm/bin/jadd
  # Use Java 11 as the global (default is set at system, explicilty define the one we wanna use though as java 11)
  jenv global 11.0
}

installZshThemes() {
  # Install powerlevel9k
  if [ ! -d "$ZSH_CUSTOM/themes/themes/powerlevel9k" ]; then
    echo "Installing PowerLevel9K ⏫"
    git clone https://github.com/bhilburn/powerlevel9k.git $HOME/.oh-my-zsh/custom/themes/powerlevel9k
  fi

  if [ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
    echo "Installing Spaceship 🚀"
    git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
  fi
}

main() {
  if [ "$OSTYPE" = linux-gnu ]; then
    linuxinit
  else
    macinit
  fi

  # Create a bin folder for user scripts
  if [ ! -d "$HOME/bin" ]; then
    mkdir $HOME/bin
  fi

  # Symlink all files in .yadm/bin to bin/*, these are custom scripts
  for file in $HOME/.yadm/bin/*; do
    ln -s ${file} $HOME/bin/${file##*/}
  done

  # Install oh-my-zsh
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing oh-my-zsh 💻"
    git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
  fi

  installZshThemes

  # Create symlinks for vscode settings if installed
  if [ -d "$HOME/Library/Application\ Support/Code" ]; then
    echo "Symlinking vscode settings ⚙️"
    ln -s "$HOME/.vscode/settings/settings.json" "$HOME/Library/Application\ Support/Code/User/settings.json"
  fi

  postinit

  echo "Finished setting up the environment! Changing shell to ZSH. 👍"
  # Change the shell to ZSH --- Keep this as the last line otherwise nothing will run after.
  chsh -s $(grep /zsh$ /etc/shells | tail -1)
}

main
