#!/usr/bin/env bash

# Bootstrap setup script depending on system

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  ln -s "$HOME/.yadm/Brewfile" "$HOME/Brewfile"
  brew bundle --file=$HOME/Brewfile
  $HOME/.yadm/mac/setup
fi

# if [ "$OSTYPE" = linux-gnu ]; then
#   $HOME/.yadm/linux_setup
# fi

$HOME/.yadm/post_setup

echo "Finished bootstrapping the system! 👍"