#!/usr/bin/env bash

# Wrapper script to install everything through YADM
# Installs custom binaries onto the system and then bootstraps packages through YADM.
# Created by Lewis Morgan

system_type=$(uname -s)

mac_pre_bootstrap() {
  # Dev tools required for Homebrew
  xcode-select --install
  
  # Homebrew
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install yadm
  # Setup of packages is done during bootstrap
}

linux_install() {
  for file in $HOME/.yadm/linux/bin/*; do
    ln -s $HOME/bin/${file##*/} ${file}
  done
  # Setup of packages is done during bootstrap
}

mac_pre_bootstrap

# Clone the dotfiles repository to setup everything else
yadm clone https://github.com/lewismorgan/dotfiles.git --no-bootstrap

# Create a bin folder for user scripts
if [ ! -d "$HOME/bin" ]; then
  mkdir $HOME/bin
fi

for file in $HOME/.yadm/mac/bin/*; do
  ln -s ${file} $HOME/bin/${file##*/}
done

yadm bootstrap

# Change the shell to ZSH --- Keep this as the last line otherwise nothing will run after.
chsh -s $(grep /zsh$ /etc/shells | tail -1)