#!/usr/bin/env bash

# Stuff thats not system dependent, used after system setup

# Most of the time these are already installed system wide
VERSION_NODE=12.7.0
VERSION_RUBY=2.6.3

install_packages() {
  echo "Installing global yarn packages 🧶"
  cat $HOME/.yadm/yarn.txt | xargs -L 1 yarn global add

  echo "Installing vscode packages ⚙️"
  cat $HOME/.yadm/vscode.txt | xargs -L 1 code --install-extension
}

setup_node() {
  nodenv install $VERSION_NODE

  # System installed version should always be the homebrew version
  nodenv global system
}

setup_ruby() {
  # Install rbenv default gems plugin
  git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems

  rbenv install $VERSION_RUBY
  rbenv global $VERSION_RUBY
  
  # TODO: Pick default_gems based on system
  git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
  cp $HOME/.yadm/mac/default_gems $HOME/.rbenv/default_gems
}

# Java Environments to setup
setup_jenv() {
  jenv enable-plugin export
  # Add all java environments using custom jadd script
  jadd
  # Use system as the global
  jenv global system
}

# ZSH Setup
setup_zsh() {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
  

}

cp "$HOME/.yadm/.env" "$HOME/.env"
setup_ruby
install_packages
setup_jenv
setup_zsh
